production:
  protect_admin_site: true
  username: phillyrb
  password: geeksnbeers
beta:
  protect_admin_site: true
  username: phillyrb
  password: geeksnbeers
development:
  protect_admin_site: false
test:
  protect_admin_site: false
